runtime : python38 
instance_class: F1 
env_variables:
  MYSQL_USER: root 
  MYSQL_PASSWORD: randomgroup2uiuc
  MYSQL_DB: apartmenthunt
  MYSQL_HOST: 35.239.142.20

handlers:
  - url: /script
    static_dir : static/script
  - url: /styles
    static_dir : static/styles

  
